#
# GROUPS
#

default_view:
  view: yes
  name: Default View
  icon: mdi:home-variant
  entities:
    - group.iphones
    - group.weather_today
    - camera.wuradar

play1_view:
  view: yes
  icon: mdi:speaker
  name: Play1 View
  entities:
    - media_player.play1

play3_view:
  view: yes
  icon: mdi:speaker
  name: Play3 View
  entities:
    - media_player.play3

mtn_view:
  view: yes
  name: Mtn View
  icon: mdi:image-filter-hdr
  entities:
    - group.mtnrpi2_status
    - group.mtnrpi3_status

# rpi2

mtnrpi2_status:
  name: MtnRpi2 Status
  icon: mdi:weather-sunset
  entities:
    - device_tracker.mtn_rpi2
    - sensor.mtnrpi2_device_name
    - sensor.mtnrpi2_device_accountid
    - sensor.mtnrpi2_balance
    - sensor.mtnrpi2_net_peer_count
    - sensor.mtnrpi2_exchange
    - sensor.mtnrpi2_connectivity
    - sensor.mtnrpi2_publickey
    - sensor.mtnrpi2_eth_blocknumber
    - sensor.mtnrpi2_eth_syncing
    - sensor.mtnrpi2_agreements_active_count
    - sensor.mtnrpi2_agreements_archive_count

mtnrpi2_agreement_view:
  view: yes
  name: MtnRpi2 Agreement View
  icon: mdi:account-card-details
  entities:
    - group.mtnrpi2_agreement0
    - group.mtnrpi2_agreement1
    - group.mtnrpi2_agreement2
    - group.mtnrpi2_agreement3
    - group.mtnrpi2_agreement4
    - group.mtnrpi2_agreement5

mtnrpi2_agreement0:
  name: 'MtnRpi2 Agreement0'
  icon: mdi:worker
  entities:
    - sensor.mtnrpi2_agreement0_name
    - sensor.mtnrpi2_agreement0_id
    - sensor.mtnrpi2_agreement0_protocol
    - sensor.mtnrpi2_agreement0_consumer
    - sensor.mtnrpi2_agreement0_create
    - sensor.mtnrpi2_agreement0_accept
    - sensor.mtnrpi2_agreement0_finalize
    - sensor.mtnrpi2_agreement0_receive
    - sensor.mtnrpi2_agreement0_start

mtnrpi2_agreement1:
  name: 'MtnRpi2 Agreement1'
  icon: mdi:worker
  entities:
    - sensor.mtnrpi2_agreement1_name
    - sensor.mtnrpi2_agreement1_id
    - sensor.mtnrpi2_agreement1_protocol
    - sensor.mtnrpi2_agreement1_consumer
    - sensor.mtnrpi2_agreement1_create
    - sensor.mtnrpi2_agreement1_accept
    - sensor.mtnrpi2_agreement1_finalize
    - sensor.mtnrpi2_agreement1_receive
    - sensor.mtnrpi2_agreement1_start

mtnrpi2_agreement2:
  name: 'MtnRpi2 Agreement2'
  icon: mdi:worker
  entities:
    - sensor.mtnrpi2_agreement2_name
    - sensor.mtnrpi2_agreement2_id
    - sensor.mtnrpi2_agreement2_protocol
    - sensor.mtnrpi2_agreement2_consumer
    - sensor.mtnrpi2_agreement2_create
    - sensor.mtnrpi2_agreement2_accept
    - sensor.mtnrpi2_agreement2_finalize
    - sensor.mtnrpi2_agreement2_receive
    - sensor.mtnrpi2_agreement2_start

mtnrpi2_agreement3:
  name: 'MtnRpi2 Agreement3'
  icon: mdi:worker
  entities:
    - sensor.mtnrpi2_agreement3_name
    - sensor.mtnrpi2_agreement3_id
    - sensor.mtnrpi2_agreement3_protocol
    - sensor.mtnrpi2_agreement3_consumer
    - sensor.mtnrpi2_agreement3_create
    - sensor.mtnrpi2_agreement3_accept
    - sensor.mtnrpi2_agreement3_finalize
    - sensor.mtnrpi2_agreement3_receive
    - sensor.mtnrpi2_agreement3_start

mtnrpi2_agreement4:
  name: 'MtnRpi2 Agreement4'
  icon: mdi:worker
  entities:
    - sensor.mtnrpi2_agreement4_name
    - sensor.mtnrpi2_agreement4_id
    - sensor.mtnrpi2_agreement4_protocol
    - sensor.mtnrpi2_agreement4_consumer
    - sensor.mtnrpi2_agreement4_create
    - sensor.mtnrpi2_agreement4_accept
    - sensor.mtnrpi2_agreement4_finalize
    - sensor.mtnrpi2_agreement4_receive
    - sensor.mtnrpi2_agreement4_start

mtnrpi2_agreement5:
  name: 'MtnRpi2 Agreement5'
  icon: mdi:worker
  entities:
    - sensor.mtnrpi2_agreement5_name
    - sensor.mtnrpi2_agreement5_id
    - sensor.mtnrpi2_agreement5_protocol
    - sensor.mtnrpi2_agreement5_consumer
    - sensor.mtnrpi2_agreement5_create
    - sensor.mtnrpi2_agreement5_accept
    - sensor.mtnrpi2_agreement5_finalize
    - sensor.mtnrpi2_agreement5_receive
    - sensor.mtnrpi2_agreement5_start

mtnrpi2_workload:
  name: MtnRpi2 Workload
  icon: mdi:worker
  entities:
    - sensor.mtnrpi2_workloads_count

mtnrpi2_attribute:
  name: MtnRpi2 Attribute
  icon: mdi:altimeter
  entities:
    - sensor.mtnrpi2_attribute_count

# rpi3

mtnrpi3_status:
  name: MtnRpi3 Status
  icon: mdi:weather-sunset
  entities:
    - device_tracker.mtn_rpi3
    - sensor.mtnrpi3_device_name
    - sensor.mtnrpi3_device_accountid
    - sensor.mtnrpi3_balance
    - sensor.mtnrpi3_net_peer_count
    - sensor.mtnrpi3_exchange
    - sensor.mtnrpi3_connectivity
    - sensor.mtnrpi3_publickey
    - sensor.mtnrpi3_eth_blocknumber
    - sensor.mtnrpi3_eth_syncing
    - sensor.mtnrpi3_agreements_active_count
    - sensor.mtnrpi3_agreements_archive_count

mtnrpi3_agreement_view:
  view: yes
  name: MtnRpi3 Agreement View
  icon: mdi:account-card-details
  entities:
    - group.mtnrpi3_agreement0
    - group.mtnrpi3_agreement1
    - group.mtnrpi3_agreement2
    - group.mtnrpi3_agreement3
    - group.mtnrpi3_agreement4
    - group.mtnrpi3_agreement5

mtnrpi3_agreement0:
  name: 'MtnRpi3 Agreement0'
  icon: mdi:worker
  entities:
    - sensor.mtnrpi3_agreement0_name
    - sensor.mtnrpi3_agreement0_id
    - sensor.mtnrpi3_agreement0_protocol
    - sensor.mtnrpi3_agreement0_consumer
    - sensor.mtnrpi3_agreement0_create
    - sensor.mtnrpi3_agreement0_accept
    - sensor.mtnrpi3_agreement0_finalize
    - sensor.mtnrpi3_agreement0_receive
    - sensor.mtnrpi3_agreement0_start

mtnrpi3_agreement1:
  name: 'MtnRpi3 Agreement1'
  icon: mdi:worker
  entities:
    - sensor.mtnrpi3_agreement1_name
    - sensor.mtnrpi3_agreement1_id
    - sensor.mtnrpi3_agreement1_protocol
    - sensor.mtnrpi3_agreement1_consumer
    - sensor.mtnrpi3_agreement1_create
    - sensor.mtnrpi3_agreement1_accept
    - sensor.mtnrpi3_agreement1_finalize
    - sensor.mtnrpi3_agreement1_receive
    - sensor.mtnrpi3_agreement1_start

mtnrpi3_agreement2:
  name: 'MtnRpi3 Agreement2'
  icon: mdi:worker
  entities:
    - sensor.mtnrpi3_agreement2_name
    - sensor.mtnrpi3_agreement2_id
    - sensor.mtnrpi3_agreement2_protocol
    - sensor.mtnrpi3_agreement2_consumer
    - sensor.mtnrpi3_agreement2_create
    - sensor.mtnrpi3_agreement2_accept
    - sensor.mtnrpi3_agreement2_finalize
    - sensor.mtnrpi3_agreement2_receive
    - sensor.mtnrpi3_agreement2_start

mtnrpi3_agreement3:
  name: 'MtnRpi3 Agreement3'
  icon: mdi:worker
  entities:
    - sensor.mtnrpi3_agreement3_name
    - sensor.mtnrpi3_agreement3_id
    - sensor.mtnrpi3_agreement3_protocol
    - sensor.mtnrpi3_agreement3_consumer
    - sensor.mtnrpi3_agreement3_create
    - sensor.mtnrpi3_agreement3_accept
    - sensor.mtnrpi3_agreement3_finalize
    - sensor.mtnrpi3_agreement3_receive
    - sensor.mtnrpi3_agreement3_start

mtnrpi3_agreement4:
  name: 'MtnRpi3 Agreement4'
  icon: mdi:worker
  entities:
    - sensor.mtnrpi3_agreement4_name
    - sensor.mtnrpi3_agreement4_id
    - sensor.mtnrpi3_agreement4_protocol
    - sensor.mtnrpi3_agreement4_consumer
    - sensor.mtnrpi3_agreement4_create
    - sensor.mtnrpi3_agreement4_accept
    - sensor.mtnrpi3_agreement4_finalize
    - sensor.mtnrpi3_agreement4_receive
    - sensor.mtnrpi3_agreement4_start

mtnrpi3_agreement5:
  name: 'MtnRpi3 Agreement5'
  icon: mdi:worker
  entities:
    - sensor.mtnrpi3_agreement5_name
    - sensor.mtnrpi3_agreement5_id
    - sensor.mtnrpi3_agreement5_protocol
    - sensor.mtnrpi3_agreement5_consumer
    - sensor.mtnrpi3_agreement5_create
    - sensor.mtnrpi3_agreement5_accept
    - sensor.mtnrpi3_agreement5_finalize
    - sensor.mtnrpi3_agreement5_receive
    - sensor.mtnrpi3_agreement5_start

mtnrpi3_workload:
  name: MtnRpi3 Workload
  icon: mdi:worker
  entities:
    - sensor.mtnrpi3_workloads_count

mtnrpi3_attribute:
  name: MtnRpi3 Attribute
  icon: mdi:altimeter
  entities:
    - sensor.mtnrpi3_attribute_count

# AGE-AT-HOME

ageathome_view:
  view: yes
  name: AgeAtHome View
  icon: mdi:human-male-female
  entities:
    - group.ageathome_mqtt
    - group.ageathome_notin_kitchen
    - group.ageathome_lastin
    - group.ageathome_whoin
    - group.ageathome_empty
    - group.ageathome_devices
    - group.ageathome_updates

ageathome_detail:
  view: true
  name: AgeAtHome Detail
  icon: mdi:image
  entities:
    - group.ageathome_kitchen
    - group.ageathome_bathroom
    - group.ageathome_frontdoor
    - group.ageathome_road

ageathome_kitchen:
  name: AgeAtHome Kitchen
  icon: mdi:human-male-female
  entities:
    - camera.imagekitchen
    - camera.camerakitchen
    - sensor.lastinkitchen
    - sensor.countkitchen
    - sensor.datekitchen
    - sensor.emptykitchen
    - sensor.imagecountkitchen
    - sensor.imagedatekitchen
    - sensor.lastinkitchen
    - sensor.whoinkitchen

ageathome_bathroom:
  name: AgeAtHome Bathroom
  icon: mdi:human-male-female
  entities:
    - camera.imagebathroom
    - camera.camerabathroom
    - sensor.lastinbathroom
    - sensor.countbathroom
    - sensor.datebathroom
    - sensor.emptybathroom
    - sensor.imagecountbathroom
    - sensor.imagedatebathroom
    - sensor.lastinbathroom
    - sensor.whoinbathroom

ageathome_frontdoor:
  name: AgeAtHome Frontdoor
  icon: mdi:human-male-female
  entities:
    - camera.imagefrontdoor
    - camera.camerafrontdoor
    - sensor.lastinfrontdoor
    - sensor.countfrontdoor
    - sensor.datefrontdoor
    - sensor.emptyfrontdoor
    - sensor.imagecountfrontdoor
    - sensor.imagedatefrontdoor
    - sensor.lastinfrontdoor
    - sensor.whoinfrontdoor

ageathome_road:
  name: AgeAtHome Road
  icon: mdi:human-male-female
  entities:
    - camera.imageroad
    - camera.cameraroad
    - sensor.lastinroad
    - sensor.countroad
    - sensor.dateroad
    - sensor.emptyroad
    - sensor.imagecountroad
    - sensor.imagedateroad
    - sensor.lastinroad
    - sensor.whoinroad

ageathome_images:
  # view: true
  name: AgeAtHome Images
  icon: mdi:image
  entities:
    - camera.imageroad
    - camera.imagefrontdoor
    - camera.imagekitchen
    - camera.imagebathroom

ageathome_cameras:
  # view: true
  name: AgeAtHome Cameras
  icon: mdi:cctv
  entities:
    - camera.cameraroad
    - camera.camerafrontdoor
    - camera.camerakitchen
    - camera.camerabathroom

weather_view:
  view: yes
  name: Weather View
  icon: mdi:weather-cloudy
  entities:
    - sensor.pws_elevation
    - camera.weatherforecast
    - group.daily_forecast

webcams_view:
  view: yes
  name: Webcams View
  icon: mdi:webcam
  entities:
    - camera.wcv80n_woodshed
    - camera.wcv80n_livingroom
    - camera.wcv80n_poolhouse_fridge
    - camera.wcv80n_interior_gate
    - camera.wcv80n_kitchen
    - camera.wcv80n_poolhouse_exterior
    - camera.wcv80n_dogyard
    - camera.wcv80n_dogshedmiddle
    - camera.wcv80n_dogshedfront
    - camera.wcv80n_dogshed_interior
    - camera.wcv80n_pondview
    - camera.wcv80n_gravelpad
    - camera.wcv80n_upperpath
    - camera.wcv80n_laundry
    - camera.wcv80n_foyer
    - camera.wcv80n_frontwalk
    - camera.wcv80n_dogpond
    - camera.wcv80n_poolhousestereo
    - camera.wcv80n_diningroom
    - camera.wcv80n_backyard

mediaplayers_view:
  view: yes
  name: Mediaplayers View
  icon: mdi:television
  entities:
    - group.david_plex
    - media_player.apple_tv
    - media_player.davidpro
    - media_player.dcms_iphone
    - media_player.fire_tv
    - media_player.kelimac
    - media_player.kitchen
    - media_player.plex
    - media_player.plex_web_safari
    - media_player.poolhouse

david_plex:
  name: DAVID PLEX
  icon: mdi:television-classic
  entities:
    - sensor.david_plex

status_view:
  view: yes
  name: Status View
  icon: mdi:sitemap
  entities:
    - group.system_status
    - group.network_status
    - group.tivo_status
    - group.webcam_status
    - group.sonos_play1
    - group.sonos_play3

sonos_play1:
  name: Sonos PLAY1
  entities:
    - device_tracker.sonos_play1
    - sensor.play1_state
    - sensor.play1_volume
    - sensor.play1_volume_muted
    - sensor.play1_media_content_id
    - sensor.play1_media_content_type
    - sensor.play1_media_duration
    - sensor.play1_media_title
    - sensor.play1_media_artist
    - sensor.play1_media_album_name

sonos_play3:
  name: Sonos PLAY3
  entities:
    - device_tracker.sonos_play3
    - sensor.play3_state
    - sensor.play3_volume
    - sensor.play3_volume_muted
    - sensor.play3_media_content_id
    - sensor.play3_media_content_type
    - sensor.play3_media_duration
    - sensor.play3_media_title
    - sensor.play3_media_artist
    - sensor.play3_media_album_name

system_status:
  name: System Status
  entities:
    - device_tracker.comcastgw
    - sensor.externalip
    - device_tracker.davidmac_en0
    - device_tracker.davidmac_en1
    - device_tracker.cabinmac_en0
    - device_tracker.cabinmac_wf0
    - device_tracker.microcell_poolhouse
    - device_tracker.microcell_garage
    - device_tracker.microcell_cabin
    - device_tracker.dlicontroller
    - device_tracker.envoy

network_status:
  name: Network Status
  entities:
    - device_tracker.airport_equipmentpad
    - device_tracker.airport_cabin
    - device_tracker.airport_window
    - device_tracker.airport_bedroom
    - device_tracker.airport_dogshed
    - device_tracker.airport_kitchen
    - device_tracker.airport_poolhouse
    - device_tracker.airport_woodshed
    - device_tracker.airport_lowerpath
    - device_tracker.airport_powerpole

tivo_status:
  name: TiVo Status
  entities:
    - device_tracker.tivo_poolhouse_premier
    - device_tracker.tivo_cabin_series3
    - device_tracker.tivo_poohouse_series3
    - device_tracker.tivo_stream
    - device_tracker.tivo_bedroom_series3
    - device_tracker.tivo_cabin_premiere

daily_forecast:
  name: Daily Forecast
  entities:
    - sensor.pws_weather_1d
    - sensor.pws_weather_1n
    - sensor.pws_weather_2d
    - sensor.pws_weather_2n
    - sensor.pws_weather_3d
    - sensor.pws_weather_3n
    - sensor.pws_weather_4d
    - sensor.pws_weather_4n

weather_today:
  name: Weather Today
  entities:
    - sun.sun
    - sensor.solar_angle
    - sensor.sunrise
    - sensor.pws_weather
    - sensor.pws_feelslike_f
    - sensor.pws_precip_today_in
    - sensor.pws_relative_humidity
    - sensor.pws_visibility_mi
    - sensor.pws_wind_dir
    - sensor.pws_wind_gust_mph
    - sensor.pws_wind_mph

ageathome_devices:
  name: 'AgeAtHome Devices'
  icon: mdi:lan-connect
  entities:
    - device_tracker.roughfog
    - device_tracker.quietwater
    - device_tracker.dampcloud
    - device_tracker.roughwind

ageathome_lastin:
  name: 'AgeAtHome LastIn'
  icon: mdi:home
  entities:
    - sensor.lastinkitchen
    - sensor.lastinbathroom
    - sensor.lastinroad
    - sensor.lastinfrontdoor

ageathome_empty:
  name: 'AgeAtHome Empty'
  icon: mdi:home
  entities:
    - sensor.emptykitchen
    - sensor.emptybathroom
    - sensor.emptyroad
    - sensor.emptyfrontdoor

ageathome_mqtt:
  name: 'AgeAtHome MQTT'
  icon: mdi:home
  entities:
    - camera.mqttimage
    - sensor.mqttwho
    - sensor.mqttwhat
    - sensor.mqttwhere
    - sensor.mqttwhen
    - sensor.mqttscore

ageathome_whoin:
  name: 'AgeAtHome WhoIn'
  icon: mdi:home
  entities:
    - sensor.whoinkitchen
    - sensor.whoinbathroom
    - sensor.whoinroad
    - sensor.whoinfrontdoor

ageathome_notin_kitchen:
  name: 'AgeAtHome NotIn Kitchen'
  icon: mdi:cancel
  entities:
    - binary_sensor.david_notin_kitchen
    - binary_sensor.keli_notin_kitchen
    - binary_sensor.hali_notin_kitchen
    - binary_sensor.ian_notin_kitchen
    - binary_sensor.riley_notin_kitchen
    - binary_sensor.ellen_notin_kitchen

ageathome_updates:
  name: 'AgeAtHome Updates'
  icon: mdi:home
  entities:
    - sensor.countkitchen
    - sensor.countbathroom
    - sensor.countfrontdoor
    - sensor.countroad
    - sensor.datekitchen
    - sensor.datebathroom
    - sensor.datefrontdoor
    - sensor.dateroad
    - sensor.imagecountkitchen
    - sensor.imagedatekitchen
    - sensor.imageidkitchen
    - sensor.imageclasskitchen
    - sensor.imagecountbathroom
    - sensor.imagecountfrontdoor
    - sensor.imagecountroad
    - sensor.imagedatefrontdoor
    - sensor.imagedateroad

webcam_status:
  name: WebCam Status
  entities:
    - device_tracker.poolcamera
    - device_tracker.wcv80n_backyard
    - device_tracker.wcv80n_diningroom
    - device_tracker.wcv80n_dogpond
    - device_tracker.wcv80n_dogshedfront
    - device_tracker.wcv80n_dogshed_interior
    - device_tracker.wcv80n_dogshedmiddle
    - device_tracker.wcv80n_dogyard
    - device_tracker.wcv80n_foyer
    - device_tracker.wcv80n_frontwalk
    - device_tracker.wcv80n_gravelpad
    - device_tracker.wcv80n_interior_gate
    - device_tracker.wcv80n_kitchen
    - device_tracker.wcv80n_laundry
    - device_tracker.wcv80n_livingroom
    - device_tracker.wcv80n_pondview
    - device_tracker.wcv80n_poolhouse_exterior
    - device_tracker.wcv80n_poolhouse_fridge
    - device_tracker.wcv80n_poolhousestereo
    - device_tracker.wcv80n_upperpath
    - device_tracker.wcv80n_woodshed

iphones:
  name: iPhones
  entities:
    - device_tracker.kelis_iphone
    - device_tracker.davids_iphone
    - device_tracker.ellens_iphone
    - device_tracker.davidsipadmini
    - device_tracker.davidcsapple_watch
    - device_tracker.kelisiphone7
    - device_tracker.dcmsiphone
    - device_tracker.ellensiphone5
    - device_tracker.halisiphone
    - device_tracker.ianmartinsiphone
    - device_tracker.rileysiphone5
